name: Atualizar Holders Diariamente

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Força a permissão de escrita diretamente no nível do Job
    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Garante que ele pegue todo o histórico para poder fazer o push

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run collector
        run: python update_holders.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add holders.json
          git commit -m "Update holders data" || echo "Sem mudanças para salvar"
          git push origin main
